//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcInternetShop.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostan
    {
        public Ostan()
        {
            this.Cities = new HashSet<City>();
            this.Resellers = new HashSet<Reseller>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Reseller> Resellers { get; set; }
    }
}
