//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcInternetShop.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.FactorItems = new HashSet<FactorItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Summery { get; set; }
        public int GroupId { get; set; }
        public decimal Price { get; set; }
        public string Url { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public int Like { get; set; }
        public int Dislike { get; set; }
        public bool Enabled { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<FactorItem> FactorItems { get; set; }
        public virtual Group Group { get; set; }
    }
}
