//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcInternetShop.Models.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reseller
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OstanId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
    
        public virtual City City { get; set; }
        public virtual Ostan Ostan { get; set; }
    }
}
